---
- id: helm-schema
  args: []
  description: Uses helm-schema to create a jsonschema.
  entry: helm-schema
  files: ^(Chart|values)\.yaml$
  language: script
  name: Helm Schema
  require_serial: true
