---
name: build and test

on: push

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: helm-schema-tarball
          path: dist/helm-schema_*-next_Linux_x86_64.tar.gz
  test:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download helm-schema
        uses: actions/download-artifact@v4
        with:
          name: helm-schema-tarball
      - shell: bash
        run: |-
          tar xf helm-schema_*-next_Linux_x86_64.tar.gz -C tests helm-schema
          cd tests && ./run.sh
